name: 'Changelog Labeler'
description: 'Automatically label new pull requests based on the Changelog'
author: 'staniulytepaulina'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    default: ${{ github.token }}
    required: false
  base-branch:
    description: 'The base branch for your repo'
    default: 'master'
    required: false
  configuration-path:
    description: 'The Changelog path for the label configuration'
    default: 'Changelogs/Unreleased.md'
    required: false
  section-symbol:
    description: 'The symbols (header) which indicate a new section in Changelog'
    default: '###'
    required: false
  label-for-umbrella:
    description: 'The label for umbrella branches'
    default: 'Umbrella'
    required: false
  label-for-release:
    description: 'The label for PR merging into release branch'
    default: 'Bug'
    required: false
  label-for-draft:
    description: 'The label for draft PR'
    default: 'Work in progress'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'