name: "Pull Request Labeler"
on: 
  pull_request:
    types: ['opened', 'reopened', 'converted_to_draft', 'ready_for_review']
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: vinted/changelog-labeler-action@master
        with:
          configuration-path: './Changelogs/Unreleased.md'